apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directory-net.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "directory-net.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.cosmosdb.connectionString }}
  cosmosdb-connection-string: {{ .Values.cosmosdb.connectionString | quote }}
  {{- else }}
  cosmosdb-connection-string: ""
  {{- end }}
