apiVersion: v1
kind: Service
metadata:
  name: {{ include "directory-net.server.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "directory-net.server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: ldap
      port: {{ .Values.server.ports.ldap }}
      targetPort: ldap
      protocol: TCP
    - name: ldaps
      port: {{ .Values.server.ports.ldaps }}
      targetPort: ldaps
      protocol: TCP
    - name: kerberos-tcp
      port: {{ .Values.server.ports.kerberos }}
      targetPort: kerberos-tcp
      protocol: TCP
    - name: kerberos-udp
      port: {{ .Values.server.ports.kerberos }}
      targetPort: kerberos-udp
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.server.ports.dns }}
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-udp
      port: {{ .Values.server.ports.dns }}
      targetPort: dns-udp
      protocol: UDP
    - name: gc
      port: {{ .Values.server.ports.gc }}
      targetPort: gc
      protocol: TCP
    - name: gcs
      port: {{ .Values.server.ports.gcs }}
      targetPort: gcs
      protocol: TCP
  selector:
    {{- include "directory-net.server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "directory-net.server.fullname" . }}-lb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "directory-net.server.labels" . | nindent 4 }}
  annotations:
    # Azure AKS
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # AWS EKS
    # service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    # GCP GKE
    # cloud.google.com/l4-rbs: "enabled"
    # networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - name: ldap
      port: {{ .Values.server.ports.ldap }}
      targetPort: ldap
      protocol: TCP
    - name: ldaps
      port: {{ .Values.server.ports.ldaps }}
      targetPort: ldaps
      protocol: TCP
    - name: kerberos-tcp
      port: {{ .Values.server.ports.kerberos }}
      targetPort: kerberos-tcp
      protocol: TCP
    - name: kerberos-udp
      port: {{ .Values.server.ports.kerberos }}
      targetPort: kerberos-udp
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.server.ports.dns }}
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-udp
      port: {{ .Values.server.ports.dns }}
      targetPort: dns-udp
      protocol: UDP
    - name: gc
      port: {{ .Values.server.ports.gc }}
      targetPort: gc
      protocol: TCP
    - name: gcs
      port: {{ .Values.server.ports.gcs }}
      targetPort: gcs
      protocol: TCP
  selector:
    {{- include "directory-net.server.selectorLabels" . | nindent 4 }}
