apiVersion: v1
kind: ConfigMap
metadata:
  name: directory-net-config
  namespace: directory-net
  labels:
    app.kubernetes.io/name: directory-net
data:
  server-appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Directory.Ldap": "Information",
          "Directory.Kerberos": "Information",
          "Directory.Dns": "Information",
          "Directory.Rpc": "Information"
        }
      },
      "CosmosDb": {
        "DatabaseName": "DirectoryNET",
        "DefaultThroughput": 1000
      },
      "Ldap": {
        "Port": 389,
        "TlsPort": 636,
        "GcPort": 3268,
        "GcTlsPort": 3269,
        "MaxConnections": 10000,
        "MaxPageSize": 1000,
        "DefaultDomain": "DC=contoso,DC=com"
      },
      "Kerberos": {
        "DefaultRealm": "CONTOSO.COM",
        "Port": 88,
        "KpasswdPort": 464,
        "MaximumSkew": "00:05:00",
        "SessionLifetime": "10:00:00",
        "MaximumRenewalWindow": "7.00:00:00"
      },
      "Dns": {
        "Port": 53,
        "Domains": ["contoso.com"],
        "DefaultTtl": 600
      },
      "NamingContexts": {
        "DomainDn": "DC=contoso,DC=com",
        "ForestDnsName": "contoso.com"
      },
      "DcNode": {
        "SiteName": "Default-First-Site-Name",
        "TenantId": "default",
        "DomainDn": "DC=contoso,DC=com",
        "BindAddresses": ["0.0.0.0"]
      }
    }
  web-appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "CosmosDb": {
        "DatabaseName": "DirectoryNET",
        "DefaultThroughput": 1000
      },
      "NamingContexts": {
        "DomainDn": "DC=contoso,DC=com",
        "ForestDnsName": "contoso.com"
      },
      "DcNode": {
        "SiteName": "Default-First-Site-Name",
        "TenantId": "default",
        "DomainDn": "DC=contoso,DC=com",
        "BindAddresses": ["0.0.0.0"]
      },
      "AllowedHosts": "*"
    }
